# username: ima_test
# password: testtest

version: "3.4"
services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    volumes:
      - ./mealie-data:/app/data/
    ports:
      - 9925:9000
    environment:
      ALLOW_SIGNUP: "false"
      LOG_LEVEL: "DEBUG"

      DB_ENGINE: sqlite

      # =====================================
      # Web Concurrency
      WEB_GUNICORN: "false"
      WORKERS_PER_CORE: 0.5
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
